name: Go

on: [push]

jobs:
  golanglint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3

  go-test-matrix:
    runs-on: ubuntu-latest

    services:
      dind:
        image: docker:23.0-dind
        ports:
          - 2375:2375
#        options: >-
#          --privileged

    steps:
      - uses: actions/checkout@v3

      - name: Use go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v -failfast -timeout 600s ./...
#        env:
#          DOCKER_HOST: tcp://dind:2375
