name: Go

on: [push]

jobs:
  golanglint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3

  go-test-matrix:
    runs-on: ubuntu-latest
    services:
      dind:
        image: docker:23.0.4-dind
        options: >-
          --privileged
          --health-cmd "docker version && docker info"    

    steps:
      - uses: actions/checkout@v3

      - name: Use go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v -race -failfast -timeout 60s ./...
        env:
          DOCKER_HOST: tcp://dind:2375
